on:
  workflow_dispatch:
    inputs: {}

jobs:
  test-across-numsharp-versions:
    runs-on: ${{ matrix.os.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        os: 
          - runs-on: windows-latest
            arch: win-x64
          - runs-on: macos-latest
            arch: osx-x64
          - runs-on: ubuntu-latest
            arch: linux-x64
        reference: 
          - 0.30.0
          - 0.20.5
          - 0.20.4
          - 0.20.3
          - 0.20.2
          - 0.20.1
          - 0.20.0
          - 0.10.6
          - 0.10.5
          - 0.10.4
          - 0.10.3
          - 0.10.2
          - 0.10.1
          - 0.10.0
          - 0.9.0
          - 0.8.3
          - 0.8.2
          - 0.8.1
          - 0.8.0
          - 0.7.4
          - 0.7.3
          - 0.7.2
          - 0.7.1
          - 0.7.0
          - 0.6.6
          - 0.6.5
          - 0.6.4
          - 0.6.3
          - 0.6.2
          - 0.6.1
          - 0.6.0
          - 0.5.0
          - 0.4.0
          - 0.3.0
          - 0.2.0
          - 0.1.0
          
    steps:
    - name: autocrlf
      if: ${{ matrix.os.arch == 'win-x64' }}
      run: git config --global core.autocrlf false
      
    - uses: actions/checkout@v1

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.net.dotnet-version }}
    
    - name: install python dependencies
      run: pip3 install -r tools/requirements.txt
    
    - name: set reference version
      run: |
        python3 tools/setversion.py nnmnkwii.tests/nnmnkwii.tests.csproj -r NumSharp=${{ matrix.reference }}
        python3 tools/setversion.py nnmnkwii/nnmnkwii.csproj -r NumSharp=${{ matrix.reference }}

    - name: restore
      run: dotnet restore nnmnkwii.tests -r ${{ matrix.os.arch }}

    - name: unit test
      run: dotnet test nnmnkwii.tests
